media: assets

content:
  - name: posts
    label: Posts
    type: collection
    path: '_posts'
    view:
      fields: [ title, date, authors ]
    fields:
      - name: layout
        label: Layout
        type: string
        default: "default"
        hidden: true
      - name: title
        label: Title
        type: string
        required: true
      - name: author
        label: Authors
        type: string
        list: true
      - name: date
        label: Date
        type: date
        required: true
      - name: thumbnail
        label: Thumbnail
        type: image
      - name: body
        label: Body
        type: rich-text
        required: true
      - name: summary
        label: Summary
        type: rich-text
        description: A short summary of the post, used in the post list and in the social preview.
  - name: calendar
    label: Calendar
    path: calendar.html
    type: file
    fields:
      - name: title
        label: Page title
        type: string
      - name: calendar-url
        label: Public URL to Google Calendar
        type: string
        description: The URL to your public Google Calendar. You can get this from the "Integrate calendar" section in your Google Calendar settings.
  - name: library
    label: Library
    type: file
    path: library.html
    fields:
      - name: title
        label: Page title
        type: string
      - name: description
        label: Page description
        type: string
      - name: books
        label: books
        type: object
        list: true
        fields:
          - name: title
            label: Book title
            type: string
          - name: cover
            label: Book cover
            type: image
          - name: class
            label: Class
            description: The class the book is used for.
            type: string
          - name: link
            label: Link
            description: Where the book can be found.
            type: string
  - name: Home
    label: Home Page
    path: index.html
    type: file
    fields:
      - name: description
        label: Description
        type: rich-text
        description: The description of the club.
      - name: meeting-schedule
        label: Meeting Schedule
        type: rich-text
        description: The schedule for club meetings.
      - name: email
        label: Contact Email
        type: string
        description: The contact email for the club.
  - name: config
    label: Site Configuration
    path: _config.yml
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
      - name: url
        label: Website URL
        type: string
      - name: baseurl
        label: Base URL
        type: string
        description: The subpath of your site, e.g. /blog

settings:
  hide: true
  content:
    merge: true