media:
  input: assets/
  output: /Wiki-Knights-Blog/assets

content:
  - name: posts
    label: Posts
    path: _posts
    type: collection
    fields:
      - name: layout
        label: Layout
        type: string
        default: "default"
        hidden: true
      - name: title
        label: Title
        type: string
        required: true
      - name: thumbnail
        label: Thumbnail
        type: image
      - name: author
        label: Authors
        type: string
        list: true